package regex

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
	"sync"
	"unicode/utf8"

	"github.com/dlclark/regexp2/v2/syntax"
)

// Generated by tools/reference/generate-regex.mjs from Node Unicode 16.0.
// Legacy canonicalization uses single-unit uppercase, excluding non-ASCII
// characters that uppercase to ASCII. Unicode simple folding is different.
//
//go:embed legacy_fold.json
var legacyFoldJSON []byte

var legacyFolds = sync.OnceValue(func() map[rune]rune {
	var table map[rune]rune
	if err := json.Unmarshal(legacyFoldJSON, &table); err != nil {
		panic(err)
	}
	return table
})

func foldUnit(ch rune) rune {
	if upper, ok := legacyFolds()[ch]; ok {
		return upper
	}
	return ch
}

func (r *Regexp) matchingRunes(input []rune) []rune {
	if !r.legacyFold {
		return input
	}
	result := make([]rune, len(input))
	for i, ch := range input {
		result[i] = foldUnit(ch)
	}
	return result
}

func assertionsPattern(pattern string, multiline, unicodeFold bool) string {
	var out strings.Builder
	class := false
	for i := 0; i < len(pattern); i++ {
		ch := pattern[i]
		if ch == '\\' && i+1 < len(pattern) {
			if !class && (pattern[i+1] == 'b' || pattern[i+1] == 'B') {
				word := `[A-Za-z0-9_]`
				if unicodeFold {
					word = `[A-Za-z0-9_\u017F\u212A]`
				}
				if pattern[i+1] == 'b' {
					fmt.Fprintf(&out, `(?:(?<=%s)(?!%s)|(?<!%s)(?=%s))`, word, word, word, word)
				} else {
					fmt.Fprintf(&out, `(?:(?<=%s)(?=%s)|(?<!%s)(?!%s))`, word, word, word, word)
				}
			} else {
				out.WriteString(pattern[i : i+2])
			}
			i++
			continue
		}
		if ch == '[' {
			class = true
		} else if ch == ']' {
			class = false
		}
		if multiline && !class && ch == '^' {
			out.WriteString(`(?:(?<![\s\S])|(?<=[\n\r\u2028\u2029]))`)
		} else if multiline && !class && ch == '$' {
			out.WriteString(`(?:(?![\s\S])|(?=[\n\r\u2028\u2029]))`)
		} else {
			out.WriteByte(ch)
		}
	}
	return out.String()
}

// Canonicalize consuming atoms rather than applying the backend's Unicode
// folding. Keep captures, assertions and backreferences in the original order.
func foldPattern(pattern string) (string, error) {
	tree, err := syntax.Parse(pattern, syntax.ParseOptions{RegexOptions: syntax.ECMAScript})
	if err != nil {
		return "", err
	}
	var out strings.Builder
	classes := map[string]string{}
	for i := 0; i < len(pattern); {
		start := i
		ch := pattern[i]
		i++
		switch ch {
		case '[':
			for i < len(pattern) {
				current := pattern[i]
				i++
				if current == '\\' && i < len(pattern) {
					i++
					continue
				}
				if current == ']' {
					break
				}
			}
			atom := pattern[start:i]
			folded, ok := classes[atom]
			if !ok {
				folded, err = foldAtom(atom)
				if err != nil {
					return "", err
				}
				classes[atom] = folded
			}
			out.WriteString(folded)
		case '(':
			if i < len(pattern) && pattern[i] == '?' {
				i++
				if i < len(pattern) && pattern[i] == '<' {
					i++
					if i < len(pattern) && (pattern[i] == '=' || pattern[i] == '!') {
						i++
					} else {
						for i < len(pattern) && pattern[i] != '>' {
							i++
						}
						if i < len(pattern) {
							i++
						}
					}
				} else if i < len(pattern) {
					i++
				}
			}
			out.WriteString(pattern[start:i])
		case ')', '*', '+', '?', '|', '^', '$':
			out.WriteByte(ch)
		case '{':
			for i < len(pattern) && (digit(pattern[i]) || pattern[i] == ',') {
				i++
			}
			if i < len(pattern) && pattern[i] == '}' {
				i++
			}
			out.WriteString(pattern[start:i])
		case '\\':
			if i == len(pattern) {
				return "", fmt.Errorf("trailing escape")
			}
			escaped := pattern[i]
			i++
			if escaped == 'k' && i < len(pattern) && pattern[i] == '<' {
				for i < len(pattern) && pattern[i] != '>' {
					i++
				}
				if i < len(pattern) {
					i++
				}
				out.WriteString(pattern[start:i])
				continue
			}
			if escaped == 'b' || escaped == 'B' {
				out.WriteString(pattern[start:i])
				continue
			}
			if digit(escaped) {
				end := i
				for end < len(pattern) && digit(pattern[end]) {
					end++
				}
				number, _ := strconv.Atoi(pattern[start+1 : end])
				if escaped != '0' && number > 0 && number < tree.Captop {
					i = end
					out.WriteString(pattern[start:i])
					continue
				}
				if escaped <= '7' {
					limit := 3
					if escaped > '3' {
						limit = 2
					}
					for i < len(pattern) && i-start-1 < limit && pattern[i] >= '0' && pattern[i] <= '7' {
						i++
					}
				}
			} else {
				count := 0
				switch escaped {
				case 'u':
					count = 4
				case 'x':
					count = 2
				case 'c':
					if i < len(pattern) && asciiLetter(pattern[i]) {
						count = 1
					}
				}
				if i+count <= len(pattern) && count > 0 {
					if escaped == 'c' {
						i += count
					} else if _, err := strconv.ParseUint(pattern[i:i+count], 16, 32); err == nil {
						i += count
					}
				}
			}
			folded, err := foldAtom(pattern[start:i])
			if err != nil {
				return "", err
			}
			out.WriteString(folded)
		default:
			value, size := utf8.DecodeRuneInString(pattern[start:])
			i = start + size
			fmt.Fprintf(&out, `\u%04X`, foldUnit(value))
		}
	}
	return out.String(), nil
}

func foldAtom(atom string) (string, error) {
	tree, err := syntax.Parse(atom, syntax.ParseOptions{RegexOptions: syntax.ECMAScript})
	if err != nil {
		return "", err
	}
	node := tree.Root.Children[0]
	var out strings.Builder
	switch node.T {
	case syntax.NtOne:
		fmt.Fprintf(&out, `\u%04X`, foldUnit(node.Ch))
	case syntax.NtMulti:
		for _, ch := range node.Str {
			fmt.Fprintf(&out, `\u%04X`, foldUnit(ch))
		}
	case syntax.NtNothing:
		out.WriteString(`[]`)
	case syntax.NtNotone:
		fmt.Fprintf(&out, `[^\u%04X]`, foldUnit(node.Ch))
	case syntax.NtSet:
		var present [65536]bool
		negative := node.Set.IsNegated()
		for ch := rune(0); ch <= 0xffff; ch++ {
			if node.Set.Contains(ch) != negative {
				present[foldUnit(ch)] = true
			}
		}
		out.WriteByte('[')
		if negative {
			out.WriteByte('^')
		}
		for start := 0; start < len(present); start++ {
			if !present[start] {
				continue
			}
			end := start
			for end+1 < len(present) && present[end+1] {
				end++
			}
			fmt.Fprintf(&out, `\u%04X`, start)
			if end != start {
				fmt.Fprintf(&out, `-\u%04X`, end)
			}
			start = end
		}
		out.WriteByte(']')
	default:
		return "", fmt.Errorf("unsupported legacy case-fold atom %q", atom)
	}
	return out.String(), nil
}
