package regex

import (
	_ "embed"
	json "encoding/json/v2"
	"fmt"
	"strings"
	"sync"
)

// Generated by tools/reference/generate-validation-unicode.mjs from Node's
// Unicode 16.0 tables and Unicode Character Database property aliases.
//
//go:embed unicode_properties.json
var unicodePropertyJSON []byte

var unicodeProperties = sync.OnceValues(func() (*propertyTables, error) {
	var data propertyTables
	err := json.Unmarshal(unicodePropertyJSON, &data)
	return &data, err
})

type propertyTables struct {
	Aliases map[string]string      `json:"aliases"`
	Ranges  map[string][][2]uint32 `json:"ranges"`
}

func propertyRanges(name string, negative bool) (string, error) {
	tables, err := unicodeProperties()
	if err != nil {
		return "", err
	}
	canonical, ok := tables.Aliases[name]
	if !ok {
		return "", fmt.Errorf("invalid Unicode property %q", name)
	}
	ranges := tables.Ranges[canonical]
	if negative {
		var inverted [][2]uint32
		var next uint32
		for _, entry := range ranges {
			if next < entry[0] {
				inverted = append(inverted, [2]uint32{next, entry[0] - 1})
			}
			next = entry[1] + 1
		}
		if next <= 0x10ffff {
			inverted = append(inverted, [2]uint32{next, 0x10ffff})
		}
		ranges = inverted
	}
	var result strings.Builder
	for _, entry := range ranges {
		fmt.Fprintf(&result, `\u{%X}`, entry[0])
		if entry[0] != entry[1] {
			fmt.Fprintf(&result, `-\u{%X}`, entry[1])
		}
	}
	return result.String(), nil
}
